"use client";

import { useEffect, useState } from "react";
import { supabase } from "@/lib/supabase";
import { motion, AnimatePresence } from "framer-motion";
import { Building2, Calendar, Users, KeyRound, CheckCircle2, AlertCircle, Loader2, Lock, GraduationCap, BadgeCheck } from "lucide-react";

interface Drive {
    id: string;
    company: string;
    drive_date: string;
    status: string;
    drive_code: string;
    expected_intake: number;
    enrolled_count: number;
    min_cgpa: number;
    min_10th: number;
    min_12th: number;
    max_backlogs: number;
    allowed_branches: string[];
    target_roles: string;
    location: string;
    source?: "tpo" | "hr";
    job_id?: string;
}

export default function StudentDrivesPage() {
    const [drives, setDrives] = useState<Drive[]>([]);
    const [loading, setLoading] = useState(true);
    const [registeredIds, setRegisteredIds] = useState<string[]>([]);
    const [codeInputs, setCodeInputs] = useState<Record<string, string>>({});
    const [joinStatus, setJoinStatus] = useState<Record<string, { type: "success" | "error"; text: string }>>({});
    const [joining, setJoining] = useState<string | null>(null);
    const [studentProfile, setStudentProfile] = useState<any>(null);

    useEffect(() => {
        const init = async () => {
            const { data: { user } } = await supabase.auth.getUser();
            if (!user) return;

            // Fetch TPO placement drives
            const { data: drivesData } = await supabase
                .from("placement_drives")
                .select("id, company, drive_date, status, drive_code, expected_intake, enrolled_count, min_cgpa, min_10th, min_12th, max_backlogs, allowed_branches, target_roles, location")
                .not("status", "eq", "Closed")
                .order("drive_date", { ascending: true });

            // Fetch HR/Recruiter job drives
            const { data: jobsData } = await supabase
                .from("jobs")
                .select("id, company_name, title, department, location, description, required_skills, min_score, created_at, job_code, min_10th, min_12th, max_backlogs, allowed_branches")
                .order("created_at", { ascending: false });

            // Normalize HR jobs into same Drive shape
            const hrDrives: Drive[] = (jobsData || []).map((j: any) => ({
                id: `hr_${j.id}`,
                company: j.company_name,
                drive_date: j.created_at,
                status: "Active",
                drive_code: j.job_code || "", // unique code generated by HR at creation
                expected_intake: 0,
                enrolled_count: 0,
                min_cgpa: j.min_score ? j.min_score / 10 : 0,
                min_10th: parseFloat(j.min_10th) || 0,
                min_12th: parseFloat(j.min_12th) || 0,
                max_backlogs: j.max_backlogs !== null && j.max_backlogs !== undefined ? parseInt(j.max_backlogs) : 99,
                allowed_branches: j.allowed_branches || [],
                target_roles: `${j.title} · ${j.department || ""}`,
                location: j.location || "",
                source: "hr" as const,
                job_id: j.id,
            }));

            const tpoDrives: Drive[] = (drivesData || []).map((d: any) => ({ ...d, source: "tpo" as const }));

            // Fetch student's registrations for both drives and jobs
            const { data: regs } = await supabase
                .from("drive_registrations")
                .select("drive_id, job_id")
                .eq("student_id", user.id);

            // Fetch student profile for eligibility preview
            const { data: profile } = await supabase
                .from("profiles")
                .select("grad_cgpa, tenth_percent, twelfth_percent, active_backlogs, branch")
                .eq("id", user.id)
                .single();

            setDrives([...tpoDrives, ...hrDrives]);

            // Map drive_id and hr_job_id correctly
            const regIds = (regs || []).map((r: any) => r.drive_id ? r.drive_id : `hr_${r.job_id}`);
            setRegisteredIds(regIds);

            setStudentProfile(profile);
            setLoading(false);
        };
        init();
    }, []);

    const handleJoin = async (driveId: string, driveCode: string) => {
        const enteredCode = codeInputs[driveId]?.trim().toUpperCase();
        if (!enteredCode) {
            setJoinStatus(prev => ({ ...prev, [driveId]: { type: "error", text: "Please enter the access code." } }));
            return;
        }

        setJoining(driveId);
        setJoinStatus(prev => ({ ...prev, [driveId]: undefined! }));

        try {
            const res = await fetch("/api/drives/join", {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify({ driveId, code: enteredCode }),
            });
            const data = await res.json();

            if (res.ok && data.success) {
                setJoinStatus(prev => ({ ...prev, [driveId]: { type: "success", text: `✅ Registered for ${data.company}!` } }));
                setRegisteredIds(prev => [...prev, driveId]);
                setCodeInputs(prev => ({ ...prev, [driveId]: "" }));
            } else {
                setJoinStatus(prev => ({ ...prev, [driveId]: { type: "error", text: data.error || "Registration failed." } }));
            }
        } finally {
            setJoining(null);
        }
    };

    const isEligible = (drive: Drive) => {
        if (!studentProfile) return null; // unknown
        const { grad_cgpa = 0, tenth_percent = 0, twelfth_percent = 0, active_backlogs = 99, branch = "" } = studentProfile;

        // If the user's branch is completely missing, explicitly prompt them to fill out their profile
        if (!branch || branch.trim() === "") return null;

        if (drive.min_cgpa > 0 && grad_cgpa < drive.min_cgpa) return false;
        if (drive.min_10th > 0 && tenth_percent < drive.min_10th) return false;
        if (drive.min_12th > 0 && twelfth_percent < drive.min_12th) return false;
        if (active_backlogs > drive.max_backlogs) return false;
        // Force branch into an array of strings just in case Supabase returns a Postgres string representation
        const branchesList = Array.isArray(drive.allowed_branches)
            ? drive.allowed_branches
            : typeof drive.allowed_branches === "string"
                ? [drive.allowed_branches]
                : [];

        if (branchesList.length > 0) {
            if (!branch || !branchesList.includes(branch)) {
                return false;
            }
        }
        return true;
    };

    if (loading) {
        return (
            <div className="flex items-center justify-center min-h-[400px]">
                <Loader2 className="w-8 h-8 animate-spin text-accent-blue" />
            </div>
        );
    }

    return (
        <div className="space-y-8 max-w-5xl mx-auto">
            {/* Header */}
            <div>
                <h1 className="text-3xl font-bold font-sora flex items-center gap-3">
                    <Building2 className="w-7 h-7 text-accent-blue" />
                    Placement Drives
                </h1>
                <p className="text-text-secondary mt-1">
                    {drives.length} active drive{drives.length !== 1 ? "s" : ""} open for registration. Enter the access code from your TPO to join.
                </p>
            </div>

            {drives.length === 0 ? (
                <div className="text-center py-24 space-y-4">
                    <Building2 className="w-14 h-14 text-text-secondary opacity-30 mx-auto" />
                    <h3 className="text-xl font-bold text-text-secondary">No Active Drives</h3>
                    <p className="text-sm text-text-secondary">Check back later or contact your TPO for details.</p>
                </div>
            ) : (
                <div className="flex flex-col gap-5">
                    {drives.map((drive, i) => {
                        const eligible = isEligible(drive);
                        const registered = registeredIds.includes(drive.id);
                        const js = joinStatus[drive.id];

                        return (
                            <motion.div
                                key={drive.id}
                                initial={{ opacity: 0, y: 16 }}
                                animate={{ opacity: 1, y: 0 }}
                                transition={{ delay: i * 0.08 }}
                                className={`bg-bg-secondary border rounded-3xl p-6 transition-all ${registered
                                    ? "border-accent-green/40 bg-accent-green/5"
                                    : eligible === false
                                        ? "border-border-color opacity-70"
                                        : "border-border-color hover:border-accent-blue"
                                    }`}
                            >
                                <div className="flex flex-col lg:flex-row gap-6">
                                    {/* Drive Info */}
                                    <div className="flex-1 space-y-4">
                                        <div className="flex items-start justify-between gap-4">
                                            <div className="flex items-center gap-3">
                                                <div className="w-12 h-12 bg-bg-card border border-border-color rounded-2xl flex items-center justify-center shrink-0">
                                                    <Building2 className="w-6 h-6 text-text-secondary" />
                                                </div>
                                                <div>
                                                    <div className="flex items-center gap-2 flex-wrap">
                                                        <h3 className="text-xl font-bold font-sora">{drive.company}</h3>
                                                        {drive.source === "hr" && (
                                                            <span className="px-2 py-0.5 bg-orange-500/10 text-orange-400 text-[10px] font-bold rounded border border-orange-500/20 uppercase tracking-wider">By HR</span>
                                                        )}
                                                        {drive.source === "tpo" && (
                                                            <span className="px-2 py-0.5 bg-accent-blue/10 text-accent-blue text-[10px] font-bold rounded border border-accent-blue/20 uppercase tracking-wider">By TPO</span>
                                                        )}
                                                    </div>
                                                    {drive.target_roles && (
                                                        <p className="text-sm text-text-secondary mt-0.5">{drive.target_roles}</p>
                                                    )}
                                                </div>
                                            </div>

                                            {/* Status badge */}
                                            <div className="shrink-0">
                                                {registered ? (
                                                    <span className="flex items-center gap-1.5 px-3 py-1 bg-accent-green/10 text-accent-green text-xs font-bold rounded-lg border border-accent-green/20">
                                                        <BadgeCheck className="w-3.5 h-3.5" /> Registered
                                                    </span>
                                                ) : eligible === false ? (
                                                    <span className="flex items-center gap-1.5 px-3 py-1 bg-accent-red/10 text-accent-red text-xs font-bold rounded-lg border border-accent-red/20">
                                                        <AlertCircle className="w-3.5 h-3.5" /> Ineligible
                                                    </span>
                                                ) : eligible === true ? (
                                                    <span className="flex items-center gap-1.5 px-3 py-1 bg-accent-green/10 text-accent-green text-xs font-bold rounded-lg border border-accent-green/20">
                                                        <CheckCircle2 className="w-3.5 h-3.5" /> Eligible
                                                    </span>
                                                ) : (
                                                    <span className="px-3 py-1 bg-accent-yellow/10 text-accent-yellow text-xs font-bold rounded-lg border border-accent-yellow/20">
                                                        Fill Profile
                                                    </span>
                                                )}
                                            </div>
                                        </div>

                                        {/* Drive meta */}
                                        <div className="flex flex-wrap gap-3 text-sm text-text-secondary">
                                            <div className="flex items-center gap-1.5">
                                                <Calendar className="w-4 h-4" />
                                                {new Date(drive.drive_date).toLocaleDateString("en-IN", { day: "2-digit", month: "short", year: "numeric" })}
                                            </div>
                                            <div className="flex items-center gap-1.5">
                                                <Users className="w-4 h-4" />
                                                {drive.enrolled_count} / {drive.expected_intake} Seats
                                            </div>
                                            {drive.location && (
                                                <div className="flex items-center gap-1.5">
                                                    📍 {drive.location}
                                                </div>
                                            )}
                                        </div>

                                        {/* Eligibility criteria badges */}
                                        <div className="flex flex-wrap gap-2">
                                            {drive.min_cgpa > 0 && (
                                                <span className={`px-2.5 py-1 text-[11px] font-bold rounded-lg border ${studentProfile && studentProfile.grad_cgpa >= drive.min_cgpa ? "bg-accent-green/10 text-accent-green border-accent-green/20" : "bg-accent-purple/10 text-accent-purple border-accent-purple/20"}`}>
                                                    CGPA ≥ {drive.min_cgpa}
                                                </span>
                                            )}
                                            {drive.min_10th > 0 && (
                                                <span className={`px-2.5 py-1 text-[11px] font-bold rounded-lg border ${studentProfile && studentProfile.tenth_percent >= drive.min_10th ? "bg-accent-green/10 text-accent-green border-accent-green/20" : "bg-accent-blue/10 text-accent-blue border-accent-blue/20"}`}>
                                                    10th ≥ {drive.min_10th}%
                                                </span>
                                            )}
                                            {drive.min_12th > 0 && (
                                                <span className={`px-2.5 py-1 text-[11px] font-bold rounded-lg border ${studentProfile && studentProfile.twelfth_percent >= drive.min_12th ? "bg-accent-green/10 text-accent-green border-accent-green/20" : "bg-accent-blue/10 text-accent-blue border-accent-blue/20"}`}>
                                                    12th ≥ {drive.min_12th}%
                                                </span>
                                            )}
                                            {drive.max_backlogs === 0 && (
                                                <span className="px-2.5 py-1 text-[11px] font-bold rounded-lg border bg-accent-red/10 text-accent-red border-accent-red/20">
                                                    No Backlogs
                                                </span>
                                            )}
                                            {drive.allowed_branches?.length > 0 && (
                                                <span className="px-2.5 py-1 text-[11px] font-bold rounded-lg border bg-bg-card text-text-secondary border-border-color">
                                                    <GraduationCap className="w-3 h-3 inline mr-1" />
                                                    {drive.allowed_branches.join(", ")}
                                                </span>
                                            )}
                                        </div>
                                    </div>

                                    {/* Join Panel */}
                                    <div className="lg:w-64 shrink-0 space-y-3">
                                        {registered ? (
                                            <div className="flex flex-col items-center justify-center h-full gap-2 p-4 bg-accent-green/10 border border-accent-green/20 rounded-2xl text-center">
                                                <BadgeCheck className="w-8 h-8 text-accent-green" />
                                                <p className="text-sm font-bold text-accent-green">You're registered!</p>
                                                <p className="text-xs text-text-secondary">Your data has been snapshotted for this drive.</p>
                                            </div>
                                        ) : (
                                            <>
                                                <div className="relative">
                                                    <KeyRound className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-text-secondary" />
                                                    <input
                                                        className="w-full bg-bg-card border border-border-color rounded-xl pl-10 pr-4 py-3 outline-none focus:border-accent-blue transition-all font-mono text-sm tracking-widest uppercase"
                                                        placeholder="ACCESS CODE"
                                                        value={codeInputs[drive.id] || ""}
                                                        onChange={e => setCodeInputs(prev => ({ ...prev, [drive.id]: e.target.value }))}
                                                        onKeyDown={e => e.key === "Enter" && handleJoin(drive.id, drive.drive_code)}
                                                    />
                                                </div>
                                                <button
                                                    onClick={() => handleJoin(drive.id, drive.drive_code)}
                                                    disabled={joining === drive.id}
                                                    className="w-full bg-accent-blue hover:bg-blue-600 disabled:opacity-50 text-white font-bold py-3 rounded-xl transition-all flex items-center justify-center gap-2 text-sm"
                                                >
                                                    {joining === drive.id ? (
                                                        <Loader2 className="w-4 h-4 animate-spin" />
                                                    ) : (
                                                        <>
                                                            <Lock className="w-4 h-4" />
                                                            Register for Drive
                                                        </>
                                                    )}
                                                </button>

                                                <AnimatePresence>
                                                    {js && (
                                                        <motion.p
                                                            initial={{ opacity: 0 }}
                                                            animate={{ opacity: 1 }}
                                                            exit={{ opacity: 0 }}
                                                            className={`text-xs px-3 py-2 rounded-xl border ${js.type === "success" ? "bg-accent-green/10 text-accent-green border-accent-green/20" : "bg-accent-red/10 text-accent-red border-accent-red/20"}`}
                                                        >
                                                            {js.text}
                                                        </motion.p>
                                                    )}
                                                </AnimatePresence>
                                            </>
                                        )}
                                    </div>
                                </div>
                            </motion.div>
                        );
                    })}
                </div>
            )}
        </div>
    );
}
